### PR TITLE
blue pill -> red pill

### PR DESCRIPTION
**Pull request by r8921039**
fix a typo

### CODE REVIEW

**Comment by moneyball** [comment]
ACK

**Comment by jnewbery** [comment]
NACK. The reference is correct.

> You take the blue pill, the story ends, you wake up in your bed and believe whatever you want to believe. You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes.

Taking the blue pill means you wake up in your own bed.

**Comment by harding** [comment]
Agreed on NACK for the same reason as @jnewbery states.  See [Wikipedia](https://en.wikipedia.org/wiki/Red_pill_and_blue_pill).

**Comment by moneyball** [comment]
It seems premature to close just because 2 of you happen to think about it
a certain way. Let's discuss instead?

It seems we agree on the definition in Wikipedia. Taking the blue pill is
blissful ignorance. Yes? So, in the text here, being "forever lost in
wonderland" suggests to me the blue pill. Which means this PR corrected the
text.

**Comment by harding** [comment]
Reopening PR but unsubscribing myself because I'm not interested in debating movie allusions.

**Comment by r8921039** [comment]
thanks guys, i was confused.

**Pull request closed without merging**
